export type PostBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "quote"; text: string; attribution?: string }
  | { type: "image"; src: string; alt: string; caption?: string };

export type Post = {
  slug: string;
  category: { pt: string; en: string };
  title: { pt: string; en: string };
  excerpt: { pt: string; en: string };
  date: string;
  readingTime: number;
  body: { pt: PostBlock[]; en: PostBlock[] };
  draft?: boolean;
};

const p = (text: string): PostBlock => ({ type: "p", text });
const h2 = (text: string): PostBlock => ({ type: "h2", text });
const h3 = (text: string): PostBlock => ({ type: "h3", text });
const quote = (text: string, attribution?: string): PostBlock => ({
  type: "quote",
  text,
  attribution,
});

export const posts: Post[] = [
  {
    slug: "como-preparar-marca-produtos-recomendados-ias",
    category: { pt: "Growth & IA", en: "Growth & AI" },
    title: {
      pt: "Como preparar sua marca e produtos para serem recomendados pelas IAs",
      en: "How to prepare your brand and products to be recommended by AI",
    },
    excerpt: {
      pt: "A nova era da busca exige substância: conteúdo proprietário, autoridade construída e gestão ativa de reputação. Por que experiência do cliente virou alavanca de aquisição em serviços financeiros.",
      en: "The new search era demands substance: proprietary content, actively built authority, and active reputation management. Why customer experience became an acquisition lever in financial services.",
    },
    date: "2026-05-11",
    readingTime: 6,
    body: {
      pt: [
        p("Por anos, o jogo de growth digital teve uma lógica clara: comprar cliques, mensurar conversão, otimizar custo de aquisição. Marca era topo de funil; performance era fundo. Quem dominava as duas operações em silos paralelos sobrevivia bem. Eu sei como esse jogo funcionava porque trabalhei com SEM no começo da minha carreira. E sei que mudou — porque a pesquisa em si mudou."),
        p("Até janeiro de 2026, o volume de buscas com mais de quatro termos cresceu 15 vezes. No AI Mode do Google, os usuários fazem buscas duas a três vezes mais longas que as tradicionais. A pesquisa virou conversa, e quem responde melhor ganha."),
        p("Há uma assimetria crescente entre pesquisa humana e pesquisa mediada por agentes. Humanos cansam, comparam três ou quatro opções, escolhem com base no que está mais visível. Agentes processam dezenas de fontes em segundos, ponderam reputação, cruzam termos de contrato, e devolvem uma recomendação."),
        quote(
          "Se um humano fosse comprar uma câmera digital, talvez visitasse cinco sites. O agente dele vai visitar mil vezes mais. Pode chegar a cinco mil sites.",
          "Matthew Prince, CEO da Cloudflare, SXSW 2026"
        ),
        p("É mil vezes mais tráfego pra responder a mesma pergunta. Em 2024, pela primeira vez em uma década, máquinas passaram humanos: 51% do tráfego global da internet já é de bots, segundo o relatório anual da Imperva. A internet de hoje está sendo construída para máquinas, e é preciso preparar a estrutura de dados também para as máquinas."),
        p("Consumidores migram cada vez mais decisões para interface conversacional. Pesquisa recente da McKinsey aponta que instituições financeiras que dominaram a otimização pra esses modelos — disciplina nova chamada Generative Engine Optimization, ou GEO — viram crescimento de até seis vezes em tráfego orgânico não pago."),
        p("O próprio Google já reconheceu publicamente o que essa virada implica."),
        quote(
          "Brand e Performance nunca estiveram tão próximos.",
          "Ana Beatriz Amorim, Google, no Congresso de Lifestyle do Ecommerce Brasil"
        ),
        p("É a forma educada de dizer algo mais incômodo: marca sem substância deixa de existir pra IA. E como cada vez mais clientes vão chegar à decisão de compra mediada por IA, marca sem substância deixa de existir, ponto."),
        p("A pergunta certa não é mais \"minha marca tem reconhecimento?\". É \"minha marca tem material que uma IA consegue ler, atribuir e recomendar com confiança?\". A recomendação prática do Google se organiza em três pilares: conteúdo proprietário denso, autoridade externa construída ativamente, e gestão ativa de reputação."),
        h2("Pilar 1: Conteúdo proprietário estruturado"),
        p("Modelos precisam de informação que explique o que sua empresa faz, pra quem, em que condições. Pra um banco ou fintech, isso significa páginas claras de produto com critérios objetivos de elegibilidade, faixas de preço transparentes, casos de uso explicados em linguagem comum. A Google reforça que conteúdo multimodal — vídeo, imagem, texto aprofundado — tem mais peso que textos curtos genéricos. É documentação utilizável, escrita pra responder perguntas reais de cliente."),
        p("Acionável: mapeie o conteúdo proprietário da sua marca e avalie pela ótica de utilidade pra IA. Páginas institucionais vagas não servem. Servem páginas que respondem diretamente \"pra quem é isso\", \"quanto custa\", \"como funciona em três meses\". Em formato multimodal quando possível."),
        h2("Pilar 2: Autoridade externa verificável"),
        p("Modelos de linguagem inferem confiança da rede de fontes que falam de uma marca. A Google recomenda investir em blogs, artigos de opinião, podcasts e webinars que posicionem a marca como autoridade. Reviews de clientes, colaborações com creators especializados e menções em veículos confiáveis viram combustível. Em setor financeiro especificamente, a marca que produz análise pública sobre seu próprio mercado tem vantagem dupla: aparece em mais resultados de IA e ganha credibilidade orgânica que mídia paga não compra."),
        p("Acionável: identifique três tipos de produção externa que sua marca pode sustentar com qualidade — não dez. Pode ser participação regular em podcasts de setor, um blog próprio com periodicidade, ou parcerias contínuas com creators relevantes. Volume importa menos que consistência e densidade."),
        h2("Pilar 3: Gestão ativa de reputação"),
        p("A Google literalmente cita Reclame Aqui e redes sociais como pontos a monitorar. Acompanhar o que está sendo dito sobre a marca em diversas plataformas deixou de ser função reativa de comunicação e virou prática essencial pra preservar visibilidade orgânica em IA."),
        p("Aqui está o ponto que ainda não foi internalizado pela maioria dos comitês de marketing: experiência do cliente virou alavanca de aquisição. A lógica é direta. Se o cliente reclama publicamente do seu banco, essa reclamação vira texto indexável. Se a IA é treinada nesse texto, ela aprende a associar sua marca a problemas específicos. Quando outro cliente potencial perguntar \"qual o melhor banco pra X\", o modelo pondera a reputação observada."),
        p("Isso reorganiza o cálculo de unit economics. Antes, um cliente mal-atendido custava o LTV perdido daquele cliente, mais boca-a-boca negativo numa rede pequena. Agora soma-se um terceiro custo: degradação de visibilidade orgânica em IA pra novos clientes potenciais. O CAC do próximo cliente sobe porque a experiência do anterior foi ruim."),
        p("E experiência ruim raramente começa no SAC. Começa no produto que não funciona como prometido, na jornada que tem atrito desnecessário, no processo interno que joga o problema do cliente de área em área. O SAC é onde o cliente chega depois que algo já falhou antes. Dimensionar bem o atendimento é necessário, mas tratar o sintoma sem mexer na causa só adia o problema — e na era da IA, adia visivelmente, porque cada interação ruim vira dado público que ensina o modelo o que sua marca representa."),
        p("Pra setor financeiro, isso é especialmente urgente. Bancos e fintechs estão entre as empresas mais reclamadas do país por construção: alta volumetria de transações, situações emocionalmente carregadas, jornadas regulatoriamente densas. O argumento de que \"investir em experiência do cliente não tem ROI claro\" perdeu validade. O ROI passou a estar em dois lugares ao mesmo tempo: na retenção do cliente atual e no posicionamento orgânico junto a modelos de IA."),
        p("Acionável: olhe pra experiência do cliente como sistema, não como função. SAC bem dimensionado importa, mas é a última camada. As camadas anteriores — produto, jornada, processo interno — são onde a maioria das reclamações públicas se origina. Em serviços financeiros, mapear as cinco causas mais frequentes de reclamação no Reclame Aqui e atacá-las na raiz é provavelmente o investimento de growth com maior retorno marginal nos próximos seis meses. E talvez o único cujo retorno aparece em duas linhas do P&L ao mesmo tempo."),
        h2("A virada cultural"),
        p("A mudança que isso exige é cultural, não tática. Empresas acostumadas a comprar cliques tinham um luxo: o canal de aquisição era separado do canal de relacionamento. Você podia ter mídia paga ótima e atendimento medíocre, e a matemática fechava no curto prazo."),
        p("Esse divórcio acabou. Marca, performance, conteúdo e atendimento viraram quatro faces de uma mesma alavanca: o quanto sua empresa é compreendida, citada e recomendada por modelos de linguagem que cada vez mais mediam a decisão de compra. Pra setor financeiro, onde a confiança é o produto e a reputação é parte do que se vende, esse alinhamento é a infraestrutura digital finalmente refletindo o que sempre foi verdade."),
        p("Preparar marca e produtos pra serem recomendados pelas IAs é o novo trabalho de quem cuida de growth, marca e relacionamento ao mesmo tempo."),
      ],
      en: [
        p("For years, digital growth had a clear logic: buy clicks, measure conversion, optimize acquisition cost. Brand was top of funnel; performance was bottom. Companies that dominated both in parallel silos did well. I know how that game worked because I did SEM early in my career. And I know it has changed — because search itself has changed."),
        p("By January 2026, the volume of searches with more than four terms had grown 15-fold. In Google's AI Mode, users run queries two to three times longer than traditional ones. Search has become conversation, and whoever answers best wins."),
        p("There is a growing asymmetry between human search and agent-mediated search. Humans get tired, compare three or four options, choose based on what's most visible. Agents process dozens of sources in seconds, weigh reputation, cross-reference contract terms, and return a recommendation."),
        quote(
          "If a human were shopping for a digital camera, they might visit five websites. Their agent will visit a thousand times more. It could hit five thousand sites.",
          "Matthew Prince, CEO of Cloudflare, SXSW 2026"
        ),
        p("That's a thousand times more traffic to answer the same question. In 2024, for the first time in a decade, machines surpassed humans: 51% of global internet traffic is now bots, according to Imperva's annual report. Today's internet is being built for machines, and data structures need to be ready for machines too."),
        p("Consumers are migrating more and more decisions to the conversational interface. Recent McKinsey research shows that financial institutions that mastered optimization for these models — a new discipline called Generative Engine Optimization, or GEO — saw up to sixfold growth in unpaid organic traffic."),
        p("Google itself has publicly acknowledged what this shift implies."),
        quote(
          "Brand and Performance have never been so close.",
          "Ana Beatriz Amorim, Google, at the Brazilian Ecommerce Lifestyle Conference"
        ),
        p("It is the polite way of saying something more uncomfortable: brands without substance cease to exist for AI. And as more customers reach purchase decisions mediated by AI, brands without substance cease to exist, period."),
        p("The right question is no longer \"does my brand have recognition?\". It is \"does my brand have material that an AI can read, attribute, and recommend with confidence?\". Google's practical recommendation organizes around three pillars: dense proprietary content, actively built external authority, and active reputation management."),
        h2("Pillar 1: Structured proprietary content"),
        p("Models need information that explains what your company does, for whom, under what conditions. For a bank or fintech, that means clear product pages with objective eligibility criteria, transparent pricing tiers, use cases explained in plain language. Google emphasizes that multimodal content — video, image, in-depth text — carries more weight than short generic copy. It is usable documentation, written to answer real customer questions."),
        p("Actionable: map your brand's proprietary content and evaluate it through the lens of AI usefulness. Vague institutional pages don't serve. What serves are pages that directly answer \"who is this for\", \"how much does it cost\", \"how does it work in three months\". In multimodal format where possible."),
        h2("Pillar 2: Verifiable external authority"),
        p("Language models infer trust from the network of sources that talk about a brand. Google recommends investing in blogs, opinion pieces, podcasts, and webinars that position the brand as an authority. Customer reviews, collaborations with specialized creators, and mentions in reputable outlets become fuel. In financial services specifically, the brand that produces public analysis about its own market has a double advantage: it appears in more AI results and gains organic credibility that paid media cannot buy."),
        p("Actionable: identify three types of external production your brand can sustain with quality — not ten. It could be regular appearances on industry podcasts, an owned blog with consistent cadence, or ongoing partnerships with relevant creators. Volume matters less than consistency and density."),
        h2("Pillar 3: Active reputation management"),
        p("Google literally cites Reclame Aqui and social networks as monitoring points. Tracking what is being said about your brand across platforms has stopped being a reactive communications function and become essential practice for preserving organic visibility in AI."),
        p("Here is the point most marketing committees haven't internalized yet: customer experience became an acquisition lever. The logic is direct. If a customer complains publicly about your bank, that complaint becomes indexable text. If AI trains on that text, it learns to associate your brand with specific problems. When another potential customer asks \"which is the best bank for X,\" the model weighs observed reputation."),
        p("This reorganizes unit economics math. Before, a poorly served customer cost the lost LTV of that customer, plus negative word-of-mouth in a small network. Now a third cost is added: degraded organic visibility in AI for new potential customers. The CAC of the next customer goes up because the previous one's experience was bad."),
        p("And bad experience rarely starts at the support desk. It starts in the product that doesn't work as promised, in the journey with unnecessary friction, in the internal process that bounces the customer's problem from area to area. Customer support is where the customer arrives after something has already failed. Sizing the support team well is necessary, but treating the symptom without addressing the cause only delays the problem — and in the AI era, it delays it visibly, because every bad interaction becomes public data that teaches the model what your brand represents."),
        p("For financial services, this is especially urgent. Banks and fintechs are among the most complained-about companies in Brazil by construction: high transaction volume, emotionally charged situations, regulatorily dense journeys. The argument that \"investing in customer experience has no clear ROI\" has lost validity. The ROI now lives in two places simultaneously: in retaining the current customer, and in organic positioning with AI models."),
        p("Actionable: look at customer experience as a system, not as a function. A well-sized support desk matters, but it is the last layer. The previous layers — product, journey, internal process — are where most public complaints originate. In financial services, mapping the five most frequent causes of complaint on Reclame Aqui and addressing them at the root is probably the growth investment with the highest marginal return over the next six months. And possibly the only one whose return shows up in two P&L lines at once."),
        h2("The cultural shift"),
        p("The change this requires is cultural, not tactical. Companies used to buying clicks had a luxury: the acquisition channel was separate from the relationship channel. You could have excellent paid media and mediocre service, and the math worked in the short term."),
        p("That divorce is over. Brand, performance, content, and service have become four faces of the same lever: how well your company is understood, cited, and recommended by language models that increasingly mediate purchase decisions. For financial services, where trust is the product and reputation is part of what's sold, this alignment is digital infrastructure finally reflecting what was always true."),
        p("Preparing brand and products to be recommended by AI is the new work of those who care for growth, brand, and relationship at the same time."),
      ],
    },
  },
  {
    slug: "incentivos-ia-eficiencia-tiram-empresas-do-futuro",
    category: { pt: "Estratégia & IA", en: "Strategy & AI" },
    title: {
      pt: "Eficientes, mas no passado: o paradoxo da IA corporativa",
      en: "Efficient, but stuck in the past: the corporate AI paradox",
    },
    excerpt: {
      pt: "Os três tipos de aposta em IA explicam por que o capital está fluindo pra eficiência enquanto os próximos líderes de mercado nascerão em outro lugar.",
      en: "The three-types framework for AI bets explains why capital is flowing toward efficiency while the next market leaders will be born somewhere else.",
    },
    date: "2026-05-12",
    readingTime: 7,
    body: {
      pt: [
        p("Estamos entrando no ápice da destruição criativa que Schumpeter descreveu há um século. Barreiras de entrada caem em setores que pareciam invioláveis, software vira commodity infinitamente replicável, e times pequenos coordenam frotas de agentes que trabalham 24x7 sem cansar. É reset estratégico em camadas simultâneas, e ninguém pode mais confiar nas antigas regras de competição."),
        p("Nesse contexto, fundadores estão escolhendo onde apostar e líderes incumbentes estão decidindo o que priorizar no roadmap de IA. Quase todo mundo está olhando pra mesma paisagem, mas com lentes diferentes. E é aí que aparece um problema: os incentivos racionais de curto prazo estão empurrando o capital pra um lugar que pode não ser onde os próximos líderes de mercado vão nascer."),
        h2("Os três tipos de aposta em IA, segundo Heller"),
        p("Jake Heller, fundador da Casetext (vendida pra Thomson Reuters por 650 milhões de dólares), deu uma fala no AI Startup School do Y Combinator em junho de 2025 que organiza a paisagem em três categorias. O framework foi pensado pra fundadores escolherem em que onda surfar, mas serve igualmente pra incumbentes decidirem onde alocar budget de transformação."),
        p("Basicamente, os empreendedores que querem criar uma startup em IA têm 3 tipos de empresas a criar:"),
        p("(1) Assist (Copilot) é IA que ajuda profissionais a fazer melhor o que já fazem."),
        p("(2) Replace é IA que substitui inteiramente tarefas que antes exigiam humanos."),
        p("(3) Unimaginable é IA que viabiliza capacidades que antes eram impossíveis."),
        { type: "image", src: "/images/ensaios/heller-framework-puro-pt.svg", alt: "Tabela com o framework original de Jake Heller: três tipos de aposta em IA — Assist (Copilot), Replace e Unimaginable — com definição e exemplo de cada.", caption: "Framework original de Jake Heller. Os três tipos com definição e exemplo." },
        h2("Complementando o framework"),
        p("Andrew Ng deu um argumento adjacente no World Economic Forum em Davos, janeiro de 2026: retornos reais vêm de redesenho top-down de workflow, não de experimentos bottom-up de produtividade incremental. Mapeando isso, tomo a liberdade de adicionar ao framework do Heller um critério adicional que diferencia os três tipos: a unidade de mudança."),
        p("(1) Assist otimiza tarefas dentro do processo existente."),
        p("(2) Replace substitui humanos na realização de tarefas dentro do processo existente."),
        p("(3) Unimaginable redesenha o processo."),
        p("Vale também a menção de que essas categorias não são compartimentos estanques. É muito comum começar em Assist e evoluir para Replace. CoCounsel começou como assistente legal e em 2025 já executa workflows completos. Cursor começou como autocomplete e em 2026 orquestra agentes que executam tarefas multi-arquivo. O movimento Assist → Replace é tendência, não exceção."),
        h2("Por que o capital vai pra Replace, e por que isso pode ser miopia"),
        p("Os incentivos racionais estão alinhados pra direcionar capital principalmente pra Replace. Não é coincidência. É onde o risco é menor e o retorno é tangível. É viável substituir parte das tarefas de um cargo, evals garantem precisão, e o mercado endereçável já existe: você sabe quanto custa manter um time de cem analistas, sabe que se um agente faz o trabalho de dez, o ROI é calculável antes do piloto. Demanda comprovada, métrica clara."),
        p("Assist tem desafio diferente: provar retorno incremental atribuível à ferramenta pode ser difícil. Cálculo do ROI exige medição cuidadosa que poucas empresas têm. Sem essa prova, renovar contratos vira ato de fé."),
        p("E Unimaginable enfrenta o oposto: retorno potencialmente alto, mas em mercados que talvez ainda não existam. Mais incerteza no retorno, maior risco de execução. Sem benchmark de adoção, sem caso comparável, sem framework regulatório. Em ambiente de capital caro, é onde comitês de investimento congelam."),
        p("Em contexto de juros altos no mundo todo, cenário geopolítico apertado entre guerras, tarifas e oscilações no preço do petróleo, empresas priorizam redução de despesas e investimento certeiro. Replace cabe exatamente nesse mandato."),
        p("Mas Ng trouxe um contraponto. Quando um banco usa IA pra revisar empréstimo, a versão Replace é cortar o tempo de 60 minutos pra 10, economizando hora-homem. Cliente ainda espera dias pelo email final. A versão Unimaginable é diferente. Se o processo leva milissegundos, o banco redesenha o workflow inteiro: marketing, application, risk assessment e transferência de fundos viram um loop autônomo. O resultado é produto novo, não economia: empréstimo instantâneo. A primeira empresa é um banco com overhead mais baixo. A segunda é a fintech que tira a primeira do mercado."),
        p("O ponto de Ng é seco: pare de usar IA pra pavimentar atalhos antigos. Use IA pra construir estradas novas. Focar só em eficiência pode te deixar eficiente, mas no passado. Pra incumbente, é risco existencial. Pra empreendedor, é oportunidade de criar negócio enorme."),
        p("Esse é o paradoxo que dá título a esse ensaio. Seguir os incentivos racionais de curto prazo te tira do longo prazo. O framework dos três tipos serve a três leitores diferentes, e cada um precisa fazer uma pergunta distinta. Fundador: qual onda surfar? Replace tem mercado previsível mas janela curta antes de virar commodity. Unimaginable tem risco maior e defensibilidade real. Investidor: onde alocar entre os três quadrantes? Diversificar é mais inteligente que concentrar tudo no quadrante de ROI mais visível, porque o próximo líder vai nascer no menos óbvio. Executivo incumbente: como balancear o roadmap? Se 100% do investimento de IA está em Replace, o portfolio defende posição atual, não captura a próxima."),
        h2("Como o caminho para o sucesso varia por categoria"),
        p("Confiabilidade é pré-requisito em qualquer quadrante. Sem evals rigorosos, sem critério explícito do que é \"great\" pra cada micro-tarefa, sem holdout sets pra evitar overfitting, nenhum produto de IA sai da fase de demo bonita. Esse processo é árduo, e é onde a maioria dos founders desiste. Quando a precisão fica em 60-70%, é tentador declarar vitória. Mas é entre 70% e 99% que mora a diferença entre demo viral e produto sustentável. Isso vale especialmente em domínios sensíveis como direito, saúde e serviços financeiros, onde erro destrói confiança que leva anos pra reconstruir."),
        p("O método de Heller (começar com uma dúzia de evals por prompt, iterar até a IA acertar quase tudo, adicionar mais cinquenta pra estressar casos extremos) vale igual pra qualquer dos três tipos. Mas o desafio dominante acima dessa fundação muda por categoria."),
        h3("Em Assist: provar valor e garantir adesão"),
        p("O risco dominante é de adoção e mensuração. A ferramenta funciona, IA sugere, humano aceita. O desafio é provar que o ganho é real, incremental e atribuível à ferramenta, e não a outras variáveis. Sem essa prova, a renovação trava. E mesmo com prova, se a usabilidade não fizer o profissional adotar no fluxo natural, fica esquecida."),
        h3("Em Replace: precisão técnica em escala"),
        p("O risco dominante é técnico e operacional. Se você substitui dez analistas, o output precisa ter a precisão que eles teriam. Aqui o método de evals importa em sua forma mais aguda: cada caso extremo não descoberto na operação é um cliente perdido ou uma regulação acionada. A assertividade e escala dos usos amplifica tanto o ganho quanto o risco."),
        h3("Em Unimaginable: redesenhar a partir de zero restrição"),
        p("O risco dominante é outro: inventar o que ainda não foi inventado. O ponto de partida é a dor do cliente, não a tecnologia. A pergunta que Heller propõe é a chave: como resolveríamos esse problema se não houvesse limite de trabalho e energia em uma tarefa? Assumindo restrição zero (custo de processamento, tempo humano, latência), qual é a dor real que ninguém está atendendo? Stripe Radar nasceu dessa pergunta. BeeSafe AI também. Redesenhar o processo a partir dessa pergunta é o que diferencia Unimaginable de Replace bem feito. Construir Unimaginable é tecnicamente difícil exatamente por isso. Mas é essa dificuldade que cria moat."),
        h2("O ciclo curto e o ciclo longo"),
        p("A tese de Schumpeter sobre destruição criativa nunca foi sobre saudosismo. Foi sobre o fato de que mercados maduros são derrubados não por quem otimiza o produto existente, mas por quem cria a categoria seguinte. IA é o ferramental mais poderoso que essa lógica já teve. O capital vai pra Replace por motivos racionais de curto prazo, e Replace vai gerar muito valor nessa década. Mas os próximos líderes de mercado vão nascer no Unimaginable."),
        p("Quem só fizer eficiência com IA pode estar fazendo bem feito o jogo errado."),
        { type: "image", src: "/images/ensaios/assist-replace-unimaginable-pt.svg", alt: "Tabela comparativa completa dos três tipos de aposta em IA: Assist (Copilot), Replace e Unimaginable, comparados em unidade da mudança, mercado endereçável, nível de risco, como ter sucesso e exemplos.", caption: "Framework completo: os três tipos comparados em unidade da mudança, mercado endereçável, risco, caminho pra ter sucesso e exemplos." },
      ],
      en: [
        p("We are entering the peak of the creative destruction Schumpeter described a century ago. Entry barriers are falling in sectors that seemed inviolable, software is becoming an infinitely replicable commodity, and small teams now coordinate fleets of agents that work 24/7 without rest. It's a strategic reset in simultaneous layers, and no one can rely on the old rules of competition anymore."),
        p("In this context, founders are choosing where to bet and leaders of incumbent companies are deciding what to prioritize on the AI roadmap. Almost everyone is looking at the same landscape, but through different lenses. And that's where a problem appears: rational short-term incentives are pushing capital toward a place that may not be where the next market leaders will be born."),
        h2("The three types of AI bets, according to Heller"),
        p("Jake Heller, founder of Casetext (sold to Thomson Reuters for $650 million), gave a talk at Y Combinator's AI Startup School in June 2025 that organizes the landscape into three categories. The framework was designed for founders to choose which wave to surf, but it works equally well for incumbents deciding where to allocate transformation budget."),
        p("Basically, entrepreneurs who want to build an AI startup have 3 types of companies they can create:"),
        p("(1) Assist (Copilot) is AI that helps professionals do better what they already do."),
        p("(2) Replace is AI that fully replaces tasks that previously required humans."),
        p("(3) Unimaginable is AI that enables capabilities that were previously impossible."),
        { type: "image", src: "/images/ensaios/heller-framework-puro-en.svg", alt: "Table with Jake Heller's original framework: three types of AI bets — Assist (Copilot), Replace, and Unimaginable — with definition and example for each.", caption: "Jake Heller's original framework. The three types with definition and example." },
        h2("Complementing the framework"),
        p("Andrew Ng made an adjacent argument at the World Economic Forum in Davos, January 2026: real returns come from top-down workflow redesign, not from bottom-up experiments of incremental productivity. Mapping this, I take the liberty to add to Heller's framework an additional criterion that differentiates the three types: the unit of change."),
        p("(1) Assist optimizes tasks within the existing process."),
        p("(2) Replace substitutes humans in performing tasks within the existing process."),
        p("(3) Unimaginable redesigns the process."),
        p("Worth also mentioning that these categories are not airtight compartments. It is very common to start as Assist and evolve to Replace. CoCounsel started as a legal assistant and by 2025 already executes complete workflows. Cursor started as autocomplete and by 2026 orchestrates agents that execute multi-file tasks. The Assist → Replace movement is a trend, not an exception."),
        h2("Why capital goes to Replace, and why this can be myopia"),
        p("Rational incentives are aligned to direct capital primarily toward Replace. It's not a coincidence. It's where the risk is lower and the return is tangible. It's viable to substitute part of the tasks of a role, evals ensure accuracy, and the addressable market already exists: you know how much it costs to maintain a team of one hundred analysts, you know that if an agent does the work of ten, ROI is calculable before the pilot. Proven demand, clear metric."),
        p("Assist has a different challenge: proving incremental return attributable to the tool can be difficult. ROI calculation requires careful measurement that few companies have. Without that proof, renewing contracts becomes an act of faith."),
        p("And Unimaginable faces the opposite: potentially high return, but in markets that may not yet exist. More uncertainty in return, higher execution risk. No adoption benchmark, no comparable case, no regulatory framework. In an environment of expensive capital, this is where investment committees freeze."),
        p("In a context of high interest rates globally, with a tight geopolitical scenario between wars, tariffs, and oil price swings, companies prioritize cost reduction and targeted investment. Replace fits exactly into that mandate."),
        p("But Ng brought a counterpoint. When a bank uses AI to review a loan, the Replace version is cutting review time from 60 minutes to 10, saving man-hours. The customer still waits days for the final email. The Unimaginable version is different. If the process takes milliseconds, the bank redesigns the entire workflow: marketing, application, risk assessment, and fund transfer become an autonomous loop. The result is a new product, not savings: instant loan. The first company is a bank with lower overhead. The second is the fintech that puts the first one out of business."),
        p("Ng's point is dry: stop using AI to pave the old cow paths. Use AI to build new highways. Focusing only on efficiency may leave you efficient, but in the past. For incumbents, it's existential risk. For entrepreneurs, it's an opportunity to create enormous new business."),
        p("This is the paradox that titles this essay. Following rational short-term incentives takes you out of the long term. The three-types framework serves three different readers, and each needs to ask a distinct question. Founder: which wave to surf? Replace has a predictable market but a short window before becoming a commodity. Unimaginable has higher risk and real defensibility. Investor: where to allocate among the three quadrants? Diversifying is smarter than concentrating everything in the quadrant with the most visible ROI, because the next leader will be born in the less obvious one. Incumbent executive: how to balance the roadmap? If 100% of the company's AI investment is in Replace, the portfolio defends current position, not captures the next."),
        h2("How the path to success varies by category"),
        p("Reliability is a prerequisite in any quadrant. Without rigorous evals, without explicit criteria for what is \"great\" for each micro-task, without holdout sets to avoid overfitting, no AI product moves beyond the beautiful demo stage. This process is arduous, and where most founders give up. When accuracy is at 60-70%, it's tempting to declare victory. But it's between 70% and 99% where the difference lives between viral demo and sustainable product. This applies especially in sensitive domains like law, health, and financial services, where product error destroys trust that takes years to rebuild."),
        p("Heller's method (starting with a dozen evals per prompt, iterating until the AI gets almost everything right, adding fifty more to stress edge cases) applies equally to any of the three types. But the dominant challenge above this foundation changes by category."),
        h3("In Assist: prove value and ensure adoption"),
        p("The dominant risk is adoption and measurement. The tool works, AI suggests, human accepts. The challenge is proving that the gain is real, incremental, and attributable to the tool, and not to other variables. Without that proof, renewal stalls. And even with proof, if the usability doesn't make the professional adopt it in the natural workflow, it gets forgotten."),
        h3("In Replace: technical accuracy at scale"),
        p("The dominant risk is technical and operational. If you replace ten analysts, the output needs to have the accuracy they would have. Here the evals method matters in its sharpest form: each edge case not discovered in operation is a lost customer or a triggered regulation. The accuracy and scale of usage amplifies both gain and risk."),
        h3("In Unimaginable: redesign from zero constraint"),
        p("The dominant risk is another: inventing what hasn't been invented yet. The starting point is the customer's pain, not technology. The question Heller proposes is the key: how would we solve this problem if there were no limit to work and energy spent on a task? Assuming zero constraint (processing cost, human time, latency), what is the real pain that nobody is addressing? Stripe Radar was born from this question. BeeSafe AI too. Redesigning the process from this question is what differentiates Unimaginable from well-done Replace. Building Unimaginable is technically difficult exactly because of this. But it's that difficulty that creates the moat."),
        h2("The short cycle and the long cycle"),
        p("Schumpeter's thesis on creative destruction was never about nostalgia. It was about the fact that mature markets are knocked down not by those who optimize the existing product, but by those who create the next category. AI is the most powerful tooling this logic has ever had. Capital will go to Replace for rational short-term reasons, and Replace will indeed generate a lot of value this decade. But the next market leaders will be born in Unimaginable."),
        p("Whoever only does efficiency with AI may be doing the wrong game very well."),
        { type: "image", src: "/images/ensaios/assist-replace-unimaginable-en.svg", alt: "Complete comparative table of the three types of AI bets: Assist (Copilot), Replace, and Unimaginable, compared across unit of change, addressable market, risk level, how to succeed, and examples.", caption: "The complete framework: the three types compared across unit of change, addressable market, risk, path to success, and examples." },
      ],
    },
  },
  {
    slug: "o-que-mudou-em-growth",
    category: { pt: "Growth & IA", en: "Growth & AI" },
    title: {
      pt: "O que está quente em growth marketing com inteligência artificial",
      en: "What is hot in growth marketing with artificial intelligence",
    },
    excerpt: {
      pt: "Voltei a mergulhar em growth depois de sete anos em outras camadas. Estamos em uma fase de transformação parecida com a que vivi quando o digital florescia.",
      en: "I returned to growth after seven years working on other strategic layers. We're in a transformation phase similar to the one I lived through when digital was blooming.",
    },
    date: "2026-05-12",
    readingTime: 6,
    body: {
      pt: [
        p("Voltei a mergulhar em growth e performance depois de sete anos trabalhando em outras camadas de estratégia e dados. A primeira surpresa foi que algumas das evoluções que eu iniciei em 2019 ainda não foram alcançadas por boa parte das empresas, principalmente em mensuração e atribuição. A segunda foi que outras coisas que pareciam fundamentais, como bid optimization, foram plataformizadas e demandam muito menos recursos hoje. A terceira foi perceber que estamos em uma fase de grande transformação, similar ao período que vivi quando trabalhei em performance marketing."),
        p("Esse ensaio é a minha leitura de temas quentes para growth hoje e do que mudou no trabalho e nas skills de quem opera essa função."),
        h2("A pesquisa se fragmentou do Google para GEO e Retail Media"),
        p("Antes a Google dominava a pesquisa e também tinha enorme acervo de display. Hoje a pesquisa está cada vez mais fragmentada. Além das buscas nas plataformas de Gen AI (ChatGPT, Gemini, Claude, Meta Search) que discorri no ensaio \"Como preparar sua marca e produtos para serem recomendados pelas IAs\", a busca também cresce direto nos grandes marketplaces e ecommerces que se consolidaram como destino."),
        p("Com os marketplaces ganhando relevância e concentração, retail media cresce como mecanismo de market share para sellers e de margem para os marketplaces. É a mídia mais fundo de funil possível. O mercado de retail media na América Latina deve dobrar até 2029 e chegar a US$ 5,4 bilhões, com Brasil crescendo 42% ao ano. No VTEX Day 2026 foi o tema com mais espaço físico do evento. VTEX, Magalu, Mercado Livre, Shopee, Drogaria SP, Panvel, PicPay. Não é hype passageiro."),
        h2("WhatsApp é o canal de maior conversão do Brasil"),
        quote(
          "O canal de maior conversão não tem barra de busca, não tem página de produto, não tem carrinho, e converte 3x mais que qualquer app.",
          "Caio Gomes, Chief AI Officer do Magalu, Congresso de Marketplace do Ecommerce Brasil"
        ),
        p("O WhatsApp é fenômeno no Brasil: 97% dos smartphones brasileiros têm o app instalado e o brasileiro o abre 30 vezes por dia."),
        p("A questão chave aqui é como fazer a conta fechar. Para manter o canal como um espaço íntimo do usuário, o WhatsApp tem uma estrutura de custos que desincentiva campanhas de marketing. No Brasil, mensagem de marketing custa cerca de R$ 0,35, utilidade R$ 0,05, autenticação R$ 0,02, e mensagem de serviço iniciada pelo cliente é gratuita dentro da janela de 24h-72h."),
        { type: "image", src: "/images/ensaios/custos-whatsapp-tipos-mensagem-pt.svg", alt: "Gráfico de barras horizontais comparando custos por tipo de mensagem no WhatsApp Business no Brasil: marketing R$ 0,35, utilidade R$ 0,05, autenticação R$ 0,02, serviço gratuito na janela de 24h-72h.", caption: "Custos por tipo de mensagem. Marketing custa 7x mais que utilidade e 17x mais que autenticação." },
        p("Mas com a estratégia certa, o ROI fecha inclusive para tickets menores: começar pelos segmentos de maior propensão (Pix não efetivado, abandono de carrinho) e usar o retorno das vendas incrementais para avançar para segmentações de conversão menor (risco de churn). A Revi apresentou ROI médio de 34x com essa tática."),
        p("Com IA, comércio conversacional deve atingir uma boa fatia do varejo e dos serviços no futuro. E vai muito além do varejo. Já é bastante presente em serviços e é possível tentar converter um bom pós-venda em recorrência direto no canal. Essa é a aposta do Magalu com a Lu."),
        h2("Agências de performance e growth marketing já têm IA em produção"),
        p("Conversei no VTEX Day com líderes de agências referência em growth e performance: Monks, Cadastra, Wicomm. Todos construíram agentes de IA proprietários encadeando fluxos completos: insights de mercado, criação de artes, desdobramento, revisão, subida de campanha."),
        p("O trabalho que move ponteiro agora é posicionamento, estratégia de canal, planejamento de incrementalidade. A agência que entendeu isso vende mais estratégia e menos execução. A que não entendeu disputa preço com automação, e essa é uma disputa que tem só um final possível."),
        h2("Plataformas integraram CRM, CDP, disparador e venda com excelente UX"),
        p("Há mais alternativas ao Salesforce, que tem uma ferramenta robusta mas complexa de operar. A Dito CRM é uma alternativa nacional. Fui uma das primeiras clientes corporativas em 2019. Hoje integram CDP omnicanal, campanhas, sales analytics, cashback e contaram de uma feature ainda no forno que propõe automaticamente a segmentação aderente, mensagem, criativo e régua de disparo quando há excesso de estoque específico. O humano só vai precisar revisar."),
        p("CRM continua sendo uma das principais fontes de dados próprios e uma das maiores armas da empresa para entender consumidores em profundidade. É a partir desse entendimento que se desenham as próximas frentes de growth. Segmentos complementares para expandir base, oportunidades de upsell, ofertas customizadas para perfis de maior valor, reativação calibrada. Quem trata CRM apenas como ferramenta de disparo de mensagem está usando uma fração do potencial."),
        h2("Mensuração ainda tenta sair de last-click para incrementalidade"),
        p("No último congresso do Ecommerce Brasil, assisti a uma palestra da DP6 sobre como equilibrar topo e fundo de funil para maximizar ROI. Os métodos são praticamente os mesmos que perseguíamos quase uma década atrás, mas melhorados: (1) Multi Touch Attribution, (2) Marketing Mix Modelling, (3) Lift Experiments com causalidade e incrementalidade. Bibliotecas open source como Robyn e Meridian tornaram MMM acessível para quem antes só tinha last-click."),
        p("Aí me perguntei por que tantas empresas ainda não chegaram lá, e por que esse tema segue relevante se a infraestrutura ficou mais acessível. Vejo três desafios. (1) Fundação de dados, com coleta sistêmica do que impacta venda e integração às ferramentas de martech. (2) Skill, com estatística e ciência de dados para rodar e interpretar os modelos. (3) Governança e cultura, que pede coragem para expor que algo não funcionou e para dividir o ROI entre canais."),
        p("Cultura é de longe o mais difícil. As pessoas têm medo de expor o que não funcionou ou de perder budget quando o ROI passa a ser dividido com outros canais. Aí vêm as desculpas, e vêm as narrativas seletivas com dados favoráveis. Esse problema não se resolve com ferramenta nenhuma, mas sim com boas habilidades corporativas."),
        h2("Outras coisas que permanecem relevantes"),
        p("Paid media ainda é essencial para compor as vendas. Os canais de cinco anos atrás seguem relevantes: search, shopping, social, display e remarketing."),
        p("Criadores e influenciadores seguem como um dos caminhos mais poderosos para construir marca, conhecimento e autoridade."),
        p("Criatividade, essência da marca e autenticidade seguem centrais para o sucesso de uma campanha. A IA acelera tudo isso, mas não substitui o trabalho de ter algo verdadeiro para dizer e dizer bem."),
        h2("Skills para a era de growth com IA"),
        p("Há doze anos performance migrou de marketeiros para engenheiros e perfis quantitativos. Era o jogo certo na época. Eu mesma construí ferramentas de otimização de lance por dia da semana, hora do dia, região, dispositivo e palavra-chave, construção automatizada de ads e otimização pós teste A/B, quando isso era diferencial competitivo real."),
        p("As plataformas hoje fazem isso melhor do que qualquer ferramenta interna conseguiria. Têm mais dados, mais sinal, e otimizam por ROI com modelos que internalizam contexto que ninguém de fora replica. Bid management super granular migrou para dentro da plataforma e não volta. Foi a maior mudança de skills que vi ao estudar as mudanças nessa área."),
        p("Isso devolve growth ao território de marketing. Posicionamento, oferta, criativo, canal, narrativa, experiência completa do cliente. Esse trabalho voltou para o centro porque a parte mecânica está commoditizada."),
        p("A fronteira quantitativa não desapareceu. Ela se deslocou. Mensuração de incrementalidade exige rigor estatístico. MMM exige fluência em causalidade. Segmentação de CRM e CDP exige raciocínio sobre cohort, lifecycle e propensão. As ferramentas avançam nessa fronteira também, e parte do trabalho quant vai migrar para dentro delas com o tempo. Mas por enquanto é onde está o diferencial técnico real, e é onde quem investe em capacidade analítica colhe vantagem desproporcional."),
        p("Tem ainda um terceiro espaço, que para mim é familiar. Quando estruturei o produto de marketing de performance da Pareto, no Rio, há doze anos, desenhei e levantei todos os processos da operação. Tínhamos automação em muitos pontos, mas que ainda dependia de humano para rodar partes do fluxo. O trabalho era arquitetar onde entrava máquina, onde entrava pessoa e como a operação fluía sem fricção. É um momento de transformação com a mesma natureza do que vivi quando o digital estava florescendo. Quem sabe desenhar esses processos, agora envolvendo agentes em vez de só scripts e regras, entrega ganho de produtividade."),
        { type: "image", src: "/images/ensaios/tres-espacos-skills-growth-pt.svg", alt: "Diagrama mostrando os três espaços de trabalho humano em growth (marketing, quantitativo, arquitetura humano-agente) acima do que já foi automatizado por plataforma ou IA.", caption: "Onde está o trabalho de growth hoje. Os três espaços do humano em cima, o que foi automatizado embaixo." },
        p("A leitura que levo desse mergulho de volta é que tem muita coisa nova em growth, mas a lógica e a mecânica de fundo continuam muito parecidas. As fronteiras se expandiram. GEO, conversational commerce e retail media abriram espaços grandes que praticamente não existiam cinco anos atrás. Mensuração de incrementalidade está finalmente acessível, mas exige cultura para virar prática. Orquestração de humano com agente não parece tão diferente do trabalho de estruturação de operação o mais automatizada possível de marketing digital que fiz em quatro empresas de setores e dimensões distintas (Rocket Internet, Pareto, T4F, Assured Labor) entre 2012 e 2019, quando o digital ainda estava se firmando."),
        p("É um momento bom para reentrar. Os espaços novos estão sendo desenhados agora, a infraestrutura de mensuração madurou, e as perguntas estratégicas se parecem com as de viradas anteriores que já vivi. Tem muito o que construir, e essa fase de construção é a que mais me interessa."),
      ],
      en: [
        p("I returned to growth and performance marketing after seven years working on other strategic and data-focused layers. The first surprise was that some of the evolutions I started in 2019 still haven't been reached by most companies, especially in measurement and attribution. The second was that other things that seemed fundamental, like bid optimization, got platformized and demand far fewer resources today. The third was realizing we're in a phase of major transformation, similar to the period I lived through working in performance marketing."),
        p("This essay is my read on the hot topics for growth today and what has changed in the work and the skills of those operating this function."),
        h2("Search fragmented away from Google toward GEO and Retail Media"),
        p("Google used to dominate search and also held the largest display inventory. Today search is increasingly fragmented. Beyond searches on Gen AI platforms (ChatGPT, Gemini, Claude, Meta Search) that I discussed in the essay \"How to prepare your brand and products to be recommended by AI\", search is also growing directly inside the major marketplaces and ecommerces that have consolidated as destinations."),
        p("As marketplaces gain relevance and concentration, retail media grows as a market share mechanism for sellers and a margin lever for the marketplaces. It is the most bottom-of-funnel media there is. The Latin American retail media market is expected to double by 2029, reaching US$ 5.4 billion, with Brazil growing 42% per year. At VTEX Day 2026 it was the topic with the largest physical footprint at the event. VTEX, Magalu, Mercado Livre, Shopee, Drogaria SP, Panvel, PicPay. This is not passing hype."),
        h2("WhatsApp is Brazil's highest-converting channel"),
        quote(
          "The highest-converting channel has no search bar, no product page, no cart, and converts 3x more than any app.",
          "Caio Gomes, Chief AI Officer at Magalu, Brazilian Ecommerce Marketplace Congress"
        ),
        p("WhatsApp is a phenomenon in Brazil: 97% of Brazilian smartphones have the app installed and the average Brazilian opens it 30 times a day."),
        p("The key question is how to make the math work. To preserve the channel as an intimate space for users, WhatsApp has a cost structure that discourages marketing campaigns. In Brazil, a marketing message costs about R$ 0.35, utility R$ 0.05, authentication R$ 0.02, and service messages initiated by the customer are free within the 24h-72h window."),
        { type: "image", src: "/images/ensaios/custos-whatsapp-tipos-mensagem-en.svg", alt: "Horizontal bar chart comparing WhatsApp Business message costs in Brazil: marketing R$ 0.35, utility R$ 0.05, authentication R$ 0.02, service free within the 24h-72h window.", caption: "Cost per message type. Marketing costs 7x more than utility and 17x more than authentication." },
        p("But with the right strategy, ROI works even for smaller tickets: start with the highest-propensity segments (failed Pix, cart abandonment) and use the return from incremental sales to advance into lower-conversion segments (churn risk). Revi presented an average ROI of 34x using this tactic."),
        p("With AI, conversational commerce should reach a meaningful share of retail and services in the future. And it goes well beyond retail. It's already heavily present in services and there's a real opportunity to convert good post-sales experience into recurrence directly in the channel. That's Magalu's bet with Lu."),
        h2("Performance and growth agencies already have AI in production"),
        p("At VTEX Day I talked with leaders of reference agencies in growth and performance: Monks, Cadastra, Wicomm. All of them built proprietary AI agents chaining complete workflows: market insights, creative production, asset variation, review, campaign launch."),
        p("The work that moves the needle now is positioning, channel strategy, incrementality planning. The agency that understood this sells more strategy and less execution. The one that didn't is competing on price against automation, and that fight has only one possible ending."),
        h2("Platforms integrated CRM, CDP, messaging and sales with great UX"),
        p("There are more alternatives to Salesforce now, which is robust but complex to operate. Dito CRM is a Brazilian alternative. I was one of their first corporate clients in 2019. Today they integrate omnichannel CDP, campaigns, sales analytics, cashback, and they shared a feature still in the oven that automatically proposes the right segmentation, message, creative and cadence when there is excess inventory of a specific product. The human only needs to review."),
        p("CRM remains one of the company's main sources of first-party data and one of its biggest weapons for understanding customers in depth. It's from that understanding that the next growth frontiers are designed. Complementary segments to expand the base, upsell opportunities, customized offers for higher-value profiles, calibrated reactivation. Treating CRM only as a message-sending tool means using a fraction of its potential."),
        h2("Measurement is still trying to move from last-click to incrementality"),
        p("At the last Ecommerce Brasil congress, I attended a talk by DP6 on how to balance top and bottom of funnel to maximize ROI. The methods are practically the same we were pursuing almost a decade ago, only better: (1) Multi Touch Attribution, (2) Marketing Mix Modelling, (3) Lift Experiments with causality and incrementality. Open source libraries like Robyn and Meridian made MMM accessible to anyone who previously only had last-click."),
        p("So I asked myself why so many companies still haven't gotten there, and why this topic remains relevant if the infrastructure has become more accessible. I see three challenges. (1) Data foundation, with systematic collection of everything that impacts sales and integration with martech tools. (2) Skill, with statistics and data science to run and interpret the models. (3) Governance and culture, which requires courage to expose what didn't work and to share ROI across channels."),
        p("Culture is by far the hardest. People fear exposing what didn't work or losing budget when ROI starts being shared with other channels. Then come the excuses, and the selective narratives with favorable data only. This problem isn't solved by any tool, it's solved by good corporate skills."),
        h2("Other things that remain relevant"),
        p("Paid media is still essential to compose sales. The channels from five years ago remain relevant: search, shopping, social, display and remarketing."),
        p("Creators and influencers remain one of the most powerful paths to build brand, awareness and authority."),
        p("Creativity, brand essence and authenticity remain central to campaign success. AI accelerates all of this, but does not replace the work of having something true to say and saying it well."),
        h2("Skills for the growth-with-AI era"),
        p("Twelve years ago performance migrated from marketers to engineers and quantitative profiles. It was the right game at the time. I myself built tools to optimize bids by day of week, time of day, region, device and keyword, automated ad construction and post-A/B test optimization, when that was a real competitive differentiator."),
        p("Today's platforms do this better than any in-house tool could. They have more data, more signal, and optimize for ROI with models that internalize context no outsider can replicate. Hyper-granular bid management migrated inside the platforms and is not coming back. It was the biggest skill shift I saw when studying the changes in this area."),
        p("This returns growth to marketing territory. Positioning, offer, creative, channel, narrative, complete customer experience. That work came back to the center because the mechanical part has been commoditized."),
        p("The quantitative frontier didn't disappear. It moved. Incrementality measurement demands statistical rigor. MMM demands fluency in causality. CRM and CDP segmentation demands reasoning about cohort, lifecycle and propensity. Tools are advancing on this frontier too, and part of the quant work will eventually migrate inside them. But for now this is where real technical differentiation lives, and where those who invest in analytical capacity reap disproportionate advantage."),
        p("There is also a third space, one that feels familiar to me. When I structured the performance marketing product at Pareto, in Rio, twelve years ago, I designed and documented all the processes of the operation. We had automation in many points, but it still required humans to run parts of the flow. The work was to architect where machines came in, where people came in, and how the operation flowed without friction. It's a transformation moment with the same nature of the one I lived when digital was blooming. Those who know how to design these processes, now involving agents instead of just scripts and rules, deliver productivity gains."),
        { type: "image", src: "/images/ensaios/tres-espacos-skills-growth-en.svg", alt: "Diagram showing the three spaces of human work in growth (marketing, quantitative, human-agent architecture) above what has already been automated by platforms or AI.", caption: "Where the work of growth lives today. The three human spaces on top, what has been automated below." },
        p("The takeaway from this re-immersion is that there's a lot of new in growth, but the underlying logic and mechanics remain very similar. The frontiers have expanded. GEO, conversational commerce and retail media opened up large spaces that practically didn't exist five years ago. Incrementality measurement is finally accessible, but requires culture to become practice. Human-agent orchestration doesn't feel that different from the work of structuring as-automated-as-possible digital marketing operations that I did at four companies of different sectors and sizes (Rocket Internet, Pareto, T4F, Assured Labor) between 2012 and 2019, when digital was still settling in."),
        p("It's a good moment to re-enter. The new spaces are being designed now, the measurement infrastructure has matured, and the strategic questions feel like the ones from previous turns I've already lived through. There's a lot to build, and this building phase is the one that interests me most."),
      ],
    },
  },
  {
    slug: "regulado-rapido",
    category: { pt: "Estratégia & IA", en: "Strategy & AI" },
    title: {
      pt: "Regulado e rápido: o falso dilema do compliance em IA",
      en: "Regulated and fast: the false dilemma of AI compliance",
    },
    excerpt: {
      pt: "A maior parte do atrito que culpamos no jurídico é, na verdade, ausência de design. Um framework para tirar IA do limbo regulatório.",
      en: "Most of the friction we blame on legal is, in fact, missing design. A framework for getting AI out of regulatory limbo.",
    },
    date: "2026-01-29",
    readingTime: 6,
    body: {
      pt: [
        p("Existe um padrão repetido em corporativos com áreas de compliance fortes: cada projeto de IA passa meses em revisão jurídica, e a frustração das equipes técnicas vai aumentando. O diagnóstico fácil é dizer que o jurídico é lento. O diagnóstico correto, na maior parte dos casos, é que o projeto chegou no jurídico mal desenhado."),
        p("[Placeholder de ensaio em construção. O conteúdo final será publicado em breve.]"),
      ],
      en: [
        p("There's a recurring pattern in corporates with strong compliance areas: each AI project spends months in legal review, and frustration on technical teams keeps growing. The easy diagnosis is to say legal is slow. The correct diagnosis, most of the time, is that the project arrived at legal poorly designed."),
        p("[Essay in progress. Final content will be published soon.]"),
      ],
    },
    draft: true,
  },
  {
    slug: "metricas-que-sobram",
    category: { pt: "Growth com IA", en: "Growth with AI" },
    title: {
      pt: "As métricas que sobram quando IA assume o operacional",
      en: "The metrics left standing when AI takes the operational layer",
    },
    excerpt: {
      pt: "CAC e LTV vão continuar. Quase todo o resto precisa ser reescrito. Um inventário honesto do que sobrevive.",
      en: "CAC and LTV survive. Almost everything else needs rewriting. An honest inventory of what makes it through.",
    },
    date: "2026-01-08",
    readingTime: 10,
    body: {
      pt: [
        p("Quando IA assume execução de boa parte do operacional de marketing e vendas, métricas tradicionais ou perdem significado ou precisam ser reescritas. CAC e LTV continuam, porque medem fluxo de caixa real. Mas taxa de conversão por etapa, tempo de resposta de SDR, número de toques antes de fechar — quase todas precisam de redefinição."),
        p("[Placeholder de ensaio em construção. O conteúdo final será publicado em breve.]"),
      ],
      en: [
        p("When AI takes execution of much of marketing and sales operations, traditional metrics either lose meaning or need to be rewritten. CAC and LTV remain, because they measure real cash flow. But conversion rate per stage, SDR response time, number of touches before closing — almost all of them need redefinition."),
        p("[Essay in progress. Final content will be published soon.]"),
      ],
    },
    draft: true,
  },
];